name: Docker Image build and delivery

on:
  push:
    branches: [ add-deploy-container-github-action ]
  pull_request:
    branches: [ add-deploy-container-github-action ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build ../../ --file Dockerfile --tag tales

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/tales